Я сделяль
sergdenisov/hh-school-2017-html-css-homework pull request #4
Opened 2018-01-04 00:54 UTC by gooverdian

Некоторые вещи не такие, как в макете, например, расстояния, или размеры шрифтов, или цвета.
Очень надеюсь, что попиксельная подгонка не является частью ДЗ.

2018-01-05 15:39 UTC, sergdenisov requested changes
Я же говорил про стайлгайд — https://google.github.io/styleguide/htmlcssguide.html#Indentation. Должно быть 2-4 отступа везде, а то читать совсем нереально код с таким форматированием.

2018-01-05 18:31 UTC, sergdenisov requested changes

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                <section class="slidable intro intro_small">
Эта секция должна лежать либо отдельно (не внутри родительской секции), или то что лежит выше (заголовок и текст) нужно тоже положить в секцию.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                    <a href="#" class="slidable__slider">
Семантически это не ссылка, а `<button>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <blockquote class="quote article__quote">
Это же не цитата, а просто кусок текста — `<p>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <!-- Картинки вместо классов CSS использованы специально, потому как это
Такие комменты не нужны в целом. Тем более, я помню что писал в соседнем пулл-реквесте =).

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <div class="col">
`<article>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <footer class="article__footer">
Ну, тогда логично было бы и заголовок обернуть в `<header>` =). Но мне кажется эти теги оверхэдом для статьи в данном случае, лучше без них.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                            <br>
Лучше не использовать `<br>`, а положить в отдельные элементы, поскольку этот контент, скорее всего, приходит с бэкенда по задумке и ты не знаешь что там может быть внутри.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <!-- Не ul, потому что внутри слайдер -->
1. Опять же, коммент не нужен и я все помню.
2. Не вижу причин не сделать `<ul>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                    <div class="col-9">
Лучше всегда четное количество использовать, 8 или 10 в данном случае, иначе у тебя отступы получаются не размером с целую колонку, а только с ее часть.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <div class="col-11">
Аналогично — 10 или 12.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                    <span class="clients__item clients_client-1"></span>
Картинки лучше через `<img>`, так как это динамический контент.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <a href="#" class="slidable__slider">
Тоже `<button>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <a href="#" class="portfolio__switch portfolio_switch-active"></a>
Нельзя модификатор для блока и его же элемент на одном HTML-элементе.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <a href="#" class="portfolio__switch"> </a>
`<button>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                <ul class="portfolio__list list list_inline list_close">
Тут ничего не должно выходить за границы страницы визуально, это же слайдер.

<img width="1440" alt="screen shot 2018-01-05 at 20 26 33" src="https://user-images.githubusercontent.com/5359222/34620525-cf190e72-f256-11e7-982a-e6c4d27b6a29.png">

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                    <div class="col-9">
Опять же, 8 или 10.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <span class="squarehead squarehead_item-1"></span>
Опять же, контент динамический скорее всего будет и делать на каждый элемент в CSS `_item-xxx` у тебя не будет возможности в реале.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <div class="col-9">
8-10.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                        <div>successful projects</div>
Отображением регистра букв (большие/маленькие) лучше всегда заниматься только в CSS.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                        <div>successful projects</div>
И тут лучше не `<div>`, а тоже что-то типа `<h5>`-`<h6>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <h2 class="title title_level-2-thin">
Нужно разбивать на 2 модификатора: `title_level-2` и `title_thin` и вешать оба.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                <div class="news__item news_reverse">
Опять же, нельзя элемент блока и модификатор этого же блока на один HTML-элемент вешать.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                    <a href="#" class="slidable__slider">
`<button>`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <div class="col headlines__item">
`<article>` наверное лучше подойдет тут.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                            <footer class="quote__footer quote_twitter">
Модификатор от блока с элементом опять же.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                        <input id="email-input" class="field__input" type="text" />
Лучше `<input>` класть прям внутрь `<label>` по возможности, тогда не нужны будут атрибуты `for` и `id`.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                                <input class="field__button" type="submit" value="Send ►" />
Лучше `<button>` всегда использовать для кнопок.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <ul class="list">
Еще хорошей семантикой считается в `<nav>` оборачивать вещи, связанные с навигацией.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                        <br>
Опять же, лучше без `<br>`.

2018-01-05 18:31 UTC, sergdenisov commented on less/article.less
> +        font-size: 1em;
Лучше не использовать `em`, если точно не уверен, что они тебе нужны =). Обычно хватает `px`.

2018-01-05 18:31 UTC, sergdenisov commented on less/article.less
> +        font-size: 1.5rem;
И особенно не мешать все вместе: `em`, `px`, `rem` для одних и тех же целей.

2018-01-05 18:31 UTC, sergdenisov commented on less/article.less
> +        letter-spacing: .07em;
Вот тут кстати подходящее место для `em`.

2018-01-05 18:31 UTC, sergdenisov commented on less/article.less
> +            width: 5em;
Опять же, лучше пиксели.

2018-01-05 18:31 UTC, sergdenisov commented on less/article.less
> +        font-size: 1.5rem;
Это касается вообще всех файлов. `em`/`rem` нужно использовать только когда есть реальная логика, которая завязана на размер шрифта.

2018-01-05 18:31 UTC, sergdenisov commented on less/field.less
> +    .field__label,
Лучше для каждой сущность писать отдельный селектор. Когда у тебя селекторы `.field__label` размазаны по файлу, понимать код тяжело. Если свойства дублируются, то можно использовать миксины.

2018-01-05 18:31 UTC, sergdenisov commented on less/field.less
> +        textarea& {
Селекторы по названиям тегов нельзя.

2018-01-05 18:31 UTC, sergdenisov commented on less/field.less
> +        width: 100%;
Это не нужно для `display: block`, он и так на всю ширину.

2018-01-05 18:31 UTC, sergdenisov commented on less/field.less
> +    .field__label {
Вообще, судя по макетам, это должен быть не лейбл, а просто `placeholder` https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder.

2018-01-05 18:31 UTC, sergdenisov commented on index.html
> +                <div class="row align-items-center footer_light footer_divider">
Нельзя использовать модификаторы без основного блока.

2018-01-05 18:31 UTC, sergdenisov commented on less/footer.less
> +    .footer_divider {
Возможно это должно быть элементом? Или название не подходящее для модификатора.

2018-01-05 18:31 UTC, sergdenisov commented on less/footer.less
> +    .footer_divider::before {
Лучше перенести выше, к самому модификатору.

2018-01-05 18:31 UTC, sergdenisov commented on less/footer.less
> +        display: block;
Можно не добавлять по идее, и так будет.

2018-01-05 18:31 UTC, sergdenisov commented on less/footer.less
> +    h4.footer__heading {
Завязки на теги быть не должно.

2018-01-05 18:31 UTC, sergdenisov commented on less/link.less
> +    .link_footer-light {
Нужно разделить на 2 модификатора.

2018-01-05 18:31 UTC, sergdenisov commented on less/list.less
> +    .list_pulled-right {
Лучше называть по смысле, а не по стилям, которые модификатор применяет.

2018-01-05 18:31 UTC, sergdenisov commented on less/list.less
> +    .list_close {
Возможно лучше сделать модификатор для элемента, а не для блока, раз тут всего 2 элемент. Выше, кстати, тоже.

2018-01-05 18:31 UTC, sergdenisov commented on less/members.less
> +@import "squarehead";
Блоки должны быть независимы, один блок не должен ничего знать о другом блоке.

2018-01-05 18:31 UTC, sergdenisov commented on less/outstanding.less
> +.outstanding {
Имена блоков и элементов по логике лучше делать существительными.

2018-01-05 18:31 UTC, sergdenisov commented on less/portfolio.less
> +        font-size: 1.05em;
Не нужно так заморачиваться с размером =). Тем более, там наверняка не получается целое число, что плохо.

2018-01-05 18:31 UTC, sergdenisov commented on less/portfolio.less
> +        height: 359px;
360.

2018-01-05 18:31 UTC, sergdenisov commented on less/portfolio.less
> +        height: 359px;
100%.

2018-01-05 18:31 UTC, sergdenisov commented on less/portfolio.less
> +    .portfolio__switch {
`switcher` тогда лучше.

2018-01-05 18:31 UTC, sergdenisov commented on less/portfolio.less
> +    .portfolio_switch-active {
Лучше прилагательные использовать в названиях модификаторов.

2018-01-05 18:31 UTC, sergdenisov commented on less/slidable.less
> +.slidable {
Лучше `.slider`.

2018-01-05 18:31 UTC, sergdenisov commented on less/slidable.less
> +    .slidable__slider {
Что-то типа `.slider__switcher`.

2018-01-05 18:31 UTC, sergdenisov commented on less/title.less
> +    .title_level-2-thin {
На 2 модификатор надо разбивать.

2018-01-05 18:31 UTC, sergdenisov commented on less/userpic.less
> +        justify-content: center !important;
Нужно сделать без `!important`.

2018-01-05 18:31 UTC, sergdenisov commented on less/variables.less
> +@color-main-background: #fff;
Лучше называть наоборот, типа `@color-background-main`. Потому что там удобней сортировать переменные по типу.

2018-01-05 18:38 UTC, gooverdian commented on index.html
> +                                <!-- Картинки вместо классов CSS использованы специально, потому как это
Этот коммент был написан до того, как я посмотрел соседний пул-реквест

2018-01-05 19:12 UTC, gooverdian commented on index.html
> +                <ul class="portfolio__list list list_inline list_close">
Вот пакость =) Это уже вопрос кросс-браузерности, в Мозилле всё ок, я поправлю для остальных

2018-01-05 19:16 UTC, sergdenisov commented on index.html
> +                <ul class="portfolio__list list list_inline list_close">
Ну это не похоже на проблемы браузеров. И пользоваться в первую очередь лучше Хромом =).

2018-01-05 19:21 UTC, gooverdian commented on less/article.less
> +        font-size: 1em;
Здесь использован 1em, что равносильно font-size: inherit; и написан он именно для этой цели, лучше написать inherit?

2018-01-05 19:43 UTC, sergdenisov commented on less/article.less
> +        font-size: 1em;
Это совсем не равносильно =). Тем более, размер шрифта и так наследуется. В данном случае вообще тогда не ясно, зачем его тут указывать? У блока выше он же уже указан.

2018-01-05 21:42 UTC, gooverdian commented on less/article.less
> +        font-size: 1em;
В HTML этот элемент лежит в каком-то тэге, например h5, как здесь.. как мне указать, что я хочу, чтобы размер шрифта совпадал с остальным текстом, независимо от тега?

2018-01-05 21:47 UTC, sergdenisov commented on less/article.less
> +        font-size: 1em;
Ну тогда ты просто задаешь размер шрифта, который тебе нужен, в `px`.

2018-01-06 00:36 UTC, gooverdian commented on less/field.less
> +        width: 100%;
https://jsfiddle.net/owwthj20/1/

2018-01-06 09:21 UTC, gooverdian commented on less/list.less
> +    .list_close {
Лучше, чтобы у всех айтемов в списке был дополнительный класс?
Или класс айтема нужно присвоить самому списку?
Ни то ни другое мне не кажется логичным, и я не могу понять, что требуется
Смысл этого модификатора - все айтемы списка располагаются близко друг к другу..

2018-01-06 09:42 UTC, gooverdian commented on less/members.less
> +@import "squarehead";
Причина этого в том, что squearehead не существует без member в рамках макета и разметки. Но да, я убрал

2018-01-06 11:01 UTC, sergdenisov commented on less/list.less
> +    .list_close {
Тут все просто — если модификатор модифицирует блок, то это модификатор блока. Если модификатор модифицирует элемент, то это модификатор элемента. Ты здесь сделал модификатор для блока, который нужен только для модификации элементов.

2018-01-06 11:20 UTC, gooverdian commented on less/list.less
> +    .list_close {
То есть делаем этот модификатор list__item_close и вешаем на каждый элемент списка? Так правильнее?

2018-01-06 11:35 UTC, sergdenisov commented on less/list.less
> +    .list_close {
Ну, на самом деле, строгих правил нет. Но я стараюсь придерживаться такой логики, что если мы модифицируем только 1 элемент с помощью модификатора, то модификатор должен быть у этого элемента. Поэтому ответ — да.

2018-01-06 11:53 UTC, gooverdian commented on less/list.less
> +    .list_close {
Это несколько расходится у меня в голове с тем, что требуется сделать, такая логика подразумевает, что у какого-то айтема будет такой модификатор, а у какого-то нет в рамках одного списка. А я этим модификатором хочу показать, что у этого **списка все** айтемы расположены рядом. Я в общем-то поправлю, это недолго, но в данном конкретном случае, я так и не согласен.

*Если модификатор модифицирует элемент, то это модификатор элемента.*
Этот модификатор модифицирует **блок** так, чтобы **все** элементы этого блока . . .

2018-01-06 12:07 UTC, sergdenisov commented on less/list.less
> +    .list_close {
Согласен, объяснение звучит логично. В данном случае можно сделать как ты говоришь, но тогда я бы переименовал модификатор, потому что в он звучит как модификатор элемента, а не списка. Список получается узкий, поэтому я назвал бы как-то типа `.list_narrow`.

2018-01-06 12:09 UTC, sergdenisov commented on less/list.less
> +    .list_inline {
Лучше, кстати, назвать как-то типа `.list_horizontal`.

2018-01-06 12:14 UTC, sergdenisov commented on less/members.less
> +@import "squarehead";
В верстке он лежит вроде просто как блок, все ок.

2018-01-06 14:19 UTC, sergdenisov requested changes

2018-01-06 14:19 UTC, sergdenisov commented on index.html
> +                                <p class="article__quote quote quote__text">
Нельзя сразу блок и его элемент на одной HTML-ноде.

2018-01-06 14:19 UTC, sergdenisov commented on index.html
> +                                <p class="article__quote quote quote__text">
Тут тоже самое.

2018-01-06 14:19 UTC, sergdenisov commented on less/all.less
> +@import "text";
Точняк, я у себя забыл заимпортить =).

2018-01-06 14:19 UTC, sergdenisov commented on less/clients.less
> +    }
Пустая строка должна быть https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

2018-01-06 14:19 UTC, sergdenisov commented on less/field.less
> +    .field-controls() {
Лучше в самый верх файла вынести.

2018-01-06 14:19 UTC, sergdenisov commented on less/field.less
> +    }
New line.

2018-01-06 14:19 UTC, sergdenisov commented on less/headlines.less
> +        font-size: 1.2rem;
`rem` лучше везде убрать, поскольку у тебя тут нет никакой завязки на изменение размера шрифта root-элемента при каких-то условиях.

2018-01-06 14:19 UTC, sergdenisov commented on less/link.less
> +        letter-spacing: -.05em;
Вкусовщина, но мне кажется наглядней писать `-0.05em` (править не обязательно).

2018-01-06 14:19 UTC, sergdenisov commented on less/list.less
> +            margin: 0 1em;
Тут тоже я бы в `px` задал.

2018-01-06 14:19 UTC, sergdenisov commented on less/mixins.less
> +}
New line.

2018-01-06 14:19 UTC, sergdenisov commented on less/news.less
> +        .news__picture {
Так нельзя по БЭМу — у тебя один элемент модифицирует другой элемент, у элементов не должно быть зависимости друг от друга, только от основного блока.

2018-01-06 14:19 UTC, sergdenisov commented on less/userpic.less
> +        margin-right: 1em;
Если явно не задаешь сущности размер шрифта, то лучше не делать завязку на `em`, поскольку у тебя получается что блок/элемент зависит от того, куда его вложишь.

2018-01-06 15:24 UTC, gooverdian commented on index.html
> +                                <p class="article__quote quote quote__text">
Ой, это я поправил в первом, и про два других забыл

2018-01-06 17:09 UTC, sergdenisov approved these changes

2022-04-11 10:51 UTC, closed without merging