Vladimir Maximov.
sergdenisov/hh-school-2017-html-css-homework pull request #8
Opened 2018-01-10 01:45 UTC by mvxio

2018-01-10 12:25 UTC, sergdenisov requested changes

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +        <script src="https://use.fontawesome.com/7dffe5d836.js"></script>
Не не, договаривались без сторонних либ же =). Все иконки либо картинкой, либо HTML Entity https://dev.w3.org/html5/html-author/charref.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +            <!-- Intro -->
Грамотная структура для того и нужна, чтобы не было потребности в таких комментах. Либо, если файл кажется слишком большой, разбить на части и заюзать шаблонизатор.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +            <!-- Intro -->
Касается всего файла.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                <div class="article__category">Comic</div>
Тут тоже какой-нибудь `<h5>` лучше.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                <div class="article__title">A million ways to die in the wild wild wild west</div>
А тут `<h4>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                        <div>Jimmy Jefferson</div>
Тут `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                            <div class="article article_activated">
Тут можно `<article>` по семантике.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                    <button class="slider__after" type="button">
`slider__button` тогда уж =).

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <div class="col-9">
Лучше четное количество колонок использовать, тут 8 или 10, иначе у тебя отступы будут не по сетке.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                            <p class="quote__text">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

`<blockquote>` — `<p>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                            <p class="quote__author">
Это по идее тоже какой-нибудь заголовок или просто `<div>`, но не параграф.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="team__member">James Philly</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="team__job">Lead Developer</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                <div class="row justify-content-around team__members">
Если ты тут флексами делаешь, то семантически тоже лучше `<ul>` — `<li>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                        <p class="facts__value">110</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                        <p class="facts__info">Successful projects</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="news__info">
Я бы тут просто `<div>` сделал или что-то другое, но это не параграф.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                <div class="news__item">
Каждая новость это по идее `<article>` или тоже `<section>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="news__title">
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                        <time datetime="08-21-2013 11:00AM">21/08/2013</time>
👍

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                <p class="stories__title">
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                <p class="stories__info">
Тоже не выглядит параграфом.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                            <div class="col stories__item">
Тут тоже можно `<article>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <div>
Лучше картинки дать класс и стили.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="twitter__user">
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="footer__title">Unicorn</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <p class="footer__title footer__title_level-2">Links</p>
`<h4>` — `<h6>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                        <div>
А вот тут скорее `<p>`.

2018-01-10 12:25 UTC, sergdenisov commented on index.html
> +                                <a class="footer__link" href="#" >Terms</a>
Отступ.

2018-01-10 12:25 UTC, sergdenisov commented on less/all.less
> +@import "defaults";
Не, это должно быть в самом верху, иначе стили могут некорретно примениться.

2018-01-10 12:25 UTC, sergdenisov commented on less/article.less
> +    }
Пустая строка нужна везде https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

2018-01-10 12:25 UTC, sergdenisov commented on less/button.less
> +    color: @color-text;
Тут импорт переменных нужно добавить.

2018-01-10 12:25 UTC, sergdenisov commented on less/control.less
> +    .control_last {
https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child

2018-01-10 12:25 UTC, sergdenisov commented on less/features.less
> +    padding: 75px 0 75px 0;
`padding: 75px 0;`?

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +    background: @background-darkest;
Лучше в переменную слово `color` добавить.

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +        &::before {
Лучше в одном стиле писать, или везде `:`, или везде `::`.

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +    .footer__link-item {
Лучше сделать один элемент `.footer__item`, а его уже модифицировать.

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +        float: right;
Лучше флексами.

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +        display: inline-block;
Это все равно не работает вроде с флоатом.

2018-01-10 12:25 UTC, sergdenisov commented on less/footer.less
> +    .footer__link-all {
Тоже лучше разруливать модификатором для `.footer__link`.

2018-01-10 12:25 UTC, sergdenisov commented on less/list-switcher.less
> +@color-list-switcher: silver;
Слова `list` и `switcher` не нужны.

2018-01-10 12:25 UTC, sergdenisov commented on less/list-switcher.less
> +@color-list-switcher-checked: OrangeRed;
Цвета лучше всегда задавать в шестнадцатеричном формате.

2018-01-10 12:25 UTC, sergdenisov commented on less/list-switcher.less
> +        background-color: @color-list-switcher;
Съехало.

2018-01-10 12:25 UTC, sergdenisov commented on less/list-switcher.less
> +            &:first-child {
Съехало.

2018-01-10 12:25 UTC, sergdenisov commented on less/news.less
> +    .news__item-reversed {
Модификатором лучше.

2018-01-10 12:25 UTC, sergdenisov commented on less/news.less
> +    .news__pic {
Лучше без сокращений, `__picture`.

2018-01-10 12:25 UTC, sergdenisov commented on less/portfolio.less
> +                .bar(auto, 0);
Съехало.

2018-01-10 12:25 UTC, sergdenisov commented on less/portfolio.less
> +    .portfolio__pic {
И тут.

2018-01-10 12:25 UTC, sergdenisov commented on less/text.less
> +        line-height: 2.0;
Зачем?))

2018-01-10 12:25 UTC, sergdenisov commented on less/twitter.less
> +    padding: 80px 0 80px;
`padding: 80px 0;`.

2018-01-10 12:25 UTC, sergdenisov commented on less/variables.less
> +@color-footer-text-lightest: #efefef;
Я бы слово `footer` убрал из всех названий.

2018-01-11 08:23 UTC, mvxio commented on less/button.less
> +    color: @color-text;
Импорт переменных есть.

2018-01-11 08:32 UTC, mvxio commented on less/all.less
> +@import "defaults";
Это — это `@import "defaults"`?

2018-01-11 08:38 UTC, mvxio commented on less/text.less
> +        line-height: 2.0;
Привёл к единому стилю — с плавающей точкой — в этом файле.

2018-01-11 08:52 UTC, sergdenisov commented on less/button.less
> +    color: @color-text;
Оу, сорри, не заметил что гитхаб скрыл.

2018-01-11 08:53 UTC, sergdenisov commented on less/all.less
> +@import "defaults";
Да.

2018-01-11 08:53 UTC, sergdenisov commented on less/text.less
> +        line-height: 2.0;
Окей, не принципиально, но не вижу в этом особого смысла.

2018-01-11 08:57 UTC, mvxio commented on less/control.less
> +    .control_last {
Оказалось, что last вообще не нужен.

2018-01-11 11:17 UTC, mvxio commented on less/text.less
> +        line-height: 2.0;
Ну, я тоже не вижу, но в какой-то момент приучился делать именно так. Если это действительно не принципиально, то не буду.

2018-01-11 11:19 UTC, mvxio commented on less/variables.less
> +@color-footer-text-lightest: #efefef;
Нужно просто давать формальные названия цветам, которые являются глобальными для нескольких лес-файлов?

2018-01-11 11:24 UTC, sergdenisov commented on less/text.less
> +        line-height: 2.0;
Ну, на мой взгляд, это никак не улучшает читаемость =). Но в тоже время сокращения тоже не всегда улучшают читаемость, к примеру, `margin: .1em`.

2018-01-11 11:27 UTC, sergdenisov commented on less/variables.less
> +@color-footer-text-lightest: #efefef;
В идеале, лучше стараться их как-то обобщить в названии, если они реально имеют что-то общее. Но на практике это не всегда получается =).

2018-01-11 23:42 UTC, mvxio commented
Внес правки

2018-01-16 12:54 UTC, sergdenisov approved these changes

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                                <article class="article article_activated">
`<article>` на предыдущую ноду вешать.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                    <ul class="nav__list portfolio__nav">
Нельзя использовать `nav__list` без основного блока `nav`.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                <ul class="list-switcher__list">
Тоже нельзя без основного блока `list-switcher`.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                        <button class="list-switcher" type="button"></button>
А тут наоборот — основного блок лежит в своем элементе, так тоже нельзя.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                            <blockquote class="quote__text">
Внутрь еще `<p>` нужно.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                    <article class="news__item news__item-reversed">
Нельзя 2 элемента одного блока на одной HTML-ноде.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                            <div>
Лишний.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                        <p class=" footer__text">
Пробел.

2018-01-16 12:54 UTC, sergdenisov commented on less/article.less
> +    }
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on index.html
> +                            <button class="button control__send_button" type="submit">Send &rtrif;</button>
1. Выглядит так, что `button` тут лишний.
2. Нельзя модификатор без элемента.

2018-01-16 12:54 UTC, sergdenisov commented on less/control.less
> +    .control__send_button {
Модификатор без элемента. Тут, видимо, нужен был просто элемент.

2018-01-16 12:54 UTC, sergdenisov commented on less/list-switcher.less
> +@color-list-switcher-checked: OrangeRed;
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on less/list-switcher.less
> +@color-list-switcher: silver;
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on less/list-switcher.less
> +        background-color: @color-list-switcher;
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on less/news.less
> +    .news__item-reversed {
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on less/portfolio.less
> +    .portfolio__pic {
Не исправлено.

2018-01-16 12:54 UTC, sergdenisov commented on less/slider.less
> +        height: 32;
В конце `px` должен быть.

2018-01-16 12:54 UTC, sergdenisov commented on less/slider.less
> +        width: 32;
И тут.

2018-07-13 13:52 UTC, closed without merging